require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion:
    3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/**/*
    - Gemfile

# Style Cops

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Metrics Cops

Metrics/BlockLength:
  Enabled: false

# Offense

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
